[package]
name = "denali-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.101"
quick-xml = { version = "0.38.2", features = ["serialize"] }
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
syn = "2.0.106"
