[package]
name = "denali-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.3"
byteorder = "1.5.0"
libc = "0.2.175"
num-traits = "0.2.19"
parking_lot = "0.12.4"
paste = "1.0.15"
thiserror = { workspace = true }

[lints]
workspace = true
