[package]
name = "denali-core-async"
version = "0.1.0"
edition = "2024"

[dependencies]
denali-core = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
