[package]
name = "chugach-windowing"
version = "0.1.0"
edition = "2024"

[dependencies]
denali-client = { workspace = true }
thiserror = { workspace = true }
frunk = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
