[package]
name = "denali-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.3"
byteorder = "1.5.0"
num-traits = "0.2.19"
paste = "1.0.15"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-seqpacket = "0.8.0"

[lints]
workspace = true