[package]
name = "denali-server"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
denali-core = { workspace = true }
denali-server-core = { workspace = true }
denali-protocol = { workspace = true }

[lints]
workspace = true
