[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
denali-core = { workspace = true }
denali-macro = { workspace = true }
denali-wayland = { workspace = true }
frunk = { workspace = true }

[[example]]
name = "simple"
path = "simple.rs"
