[package]
name = "examples"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
smol = { workspace = true }
denali-macro = { workspace = true }
denali-core = { workspace = true }
denali-client = { workspace = true }
nix = { workspace = true }
memfd = "0.6.5"

[[example]]
name = "simple"
path = "simple.rs"

[[example]]
name = "gamma"
path = "gamma.rs"
