[package]
name = "denali-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
denali-macro = { workspace = true }
denali-core = { workspace = true }
denali-client-core = { workspace = true }
denali-server-core = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
flate2 = "1.1.2"
reqwest = { version = "0.12.23", features = ["blocking"] }
tar = "0.4.44"

[lints]
workspace = true
