[package]
name = "denali-server-core"
version = "0.1.0"
edition = "2024"

[dependencies]
denali-core = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-seqpacket = { workspace = true }

[lints]
workspace = true
