[package]
name = "denali-server-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
denali-core = { workspace = true }

[lints]
workspace = true
